pkp/pkp-lib#i9963 API Endpoint to download review files
pkp/pkp-lib pull request #10112
Opened 2024-06-24 13:47 UTC by Vitaliy-1

2024-08-02 17:14 UTC, taslangraham commented
The implemented endpoint seems to support the use-case described in https://github.com/pkp/pkp-lib/issues/9964. Assigned files can be retrieved by sending the appropriate fileStage(4) in the `fileStages` param.
https://github.com/pkp/pkp-lib/blob/fe3fe7925d632fb6997237b604f3aa759b281d9d/api/v1/submissions/PKPSubmissionFileController.php#L644-L654

@Vitaliy-1 @eirikhanssen @jardakotesovec

2024-08-21 16:39 UTC, ewhanson requested changes

2026-04-17 04:04 UTC, blesildaramirez requested changes
Hi @Vitaliy-1, I requested a few changes related to OMP (allowing internal review file stage) and some fixes on the `getSchemaMap` method call (as the params were changed).
Let me know if you have any questions regarding this. Thanks!

2026-04-17 04:04 UTC, blesildaramirez commented on api/v1/submissions/PKPSubmissionFileController.php
> +            SubmissionFile::SUBMISSION_FILE_REVIEW_FILE
This also needs `SubmissionFile::SUBMISSION_FILE_INTERNAL_REVIEW_FILE` for OMP:
 
```suggestion
            SubmissionFile::SUBMISSION_FILE_REVIEW_FILE,
            SubmissionFile::SUBMISSION_FILE_INTERNAL_REVIEW_FILE,
```

2026-04-17 04:04 UTC, blesildaramirez commented on api/v1/submissions/PKPSubmissionFileController.php
> +            ->summarizeMany($files, $this->getFileGenres());
The `getSchemaMap` now has 2 params, so this should be:

```suggestion
        $items = Repo::submissionFile()
            ->getSchemaMap($submission, $this->getFileGenres())
            ->summarizeMany($files);
```

2026-04-17 04:04 UTC, blesildaramirez commented on api/v1/submissions/PKPSubmissionFileController.php
> +            $submission = Repo::submission()->get($reviewAssignment->getSubmissionId());
Related to my comment on https://github.com/pkp/pkp-lib/pull/10112/changes#r3097739123, we need to move this `$submission` declaration up, because it will be accessed outside of this if condition.

2026-04-17 04:04 UTC, blesildaramirez commented on api/v1/submissions/PKPSubmissionFileController.php
> +        if (in_array(SubmissionFile::SUBMISSION_FILE_REVIEW_FILE, $fileStages)) {
This needs to include `SubmissionFile::SUBMISSION_FILE_REVIEW_FILE` for OMP:

```suggestion
        // Get review files assigned to this reviewer (external or internal review)
        $reviewFileStages = array_intersect($fileStages, [
            SubmissionFile::SUBMISSION_FILE_REVIEW_FILE,
            SubmissionFile::SUBMISSION_FILE_INTERNAL_REVIEW_FILE,
        ]);
        if (!empty($reviewFileStages)) {
```

2026-08-18 17:59 UTC, blesildaramirez requested changes
Hi @Vitaliy-1 , based on my testing, the review assignment filter doesn't seem to work as expected. Other files from other review assignments get included when I use this endpoint:
`/api/v1/submissions/{submissionId}/files/review/{reviewAssignmentId}?fileStages=5`

<img width="967" height="551" alt="Image" src="https://github.com/user-attachments/assets/e9e3d3a2-4362-49ae-a2b9-21c832e74d79" />

Could you also check my previous review comments? https://github.com/pkp/pkp-lib/pull/10112#pullrequestreview-4125853076. These are still need to be addressed for OMP. I resolved the ones that you already fixed and irrelevant. Thanks!

2026-08-18 17:59 UTC, blesildaramirez commented on api/v1/submissions/PKPSubmissionFileController.php
> +                    ->filterByReviewRoundIds([$reviewAssignment->getReviewRoundId()])
While testing, I noticed that some files that belong to another reviewAssignmentId is included for editors when they should only see the files associated by the submitted reviewAssignmentId, so I think we need to filter this by assocId and not the reviewRoundIds?

```suggestion
                    ->filterByAssoc(Application::ASSOC_TYPE_REVIEW_ASSIGNMENT, [$reviewAssignment->getId()])
```

2026-08-18 17:59 UTC, blesildaramirez commented on api/v1/submissions/PKPSubmissionFileController.php
> +                Role::ROLE_ID_SUB_EDITOR,
Do we need to include `ROLE_ID_ASSISTANT` in the allowed roles for this? I was thinking a funding coordinator could be assigned to a submission in review stage, so maybe this needs to be adjusted? In 3.5, we allow assistant roles to access the Reviewer files via "Review Details" in the submission workflow.

2026-08-19 09:25 UTC, Vitaliy-1 commented on api/v1/submissions/PKPSubmissionFileController.php
> +                    ->filterByReviewRoundIds([$reviewAssignment->getReviewRoundId()])
Oops, looked at a wrong submission file

2026-08-19 15:27 UTC, blesildaramirez approved these changes
Hi @Vitaliy-1 , I checked your latest updates and the APIs are working well for me now for the filter by review assignment id.
Approving this although I wanted to note that there's also some adjustments to make for OMP that we might need to address on this PR:
- https://github.com/pkp/pkp-lib/pull/10112#discussion_r3097693737
- https://github.com/pkp/pkp-lib/pull/10112#discussion_r3097761036

Let me know if you have any questions. Thanks!

2026-08-19 21:56 UTC, ewhanson requested changes
Thanks @Vitaliy-1. Really just one larger question about internal security policies. And thanks @blesildaramirez for flagging the places where OMP specifics need to be considered.

2026-08-19 21:56 UTC, ewhanson commented on api/v1/submissions/PKPSubmissionFileController.php
> +use PKP\security\authorization\internal\SubmissionRequiredPolicy;
Questions about this have come up in a few different places now about not wanting to directly use internal security policies (see [this comment](https://github.com/pkp/pkp-lib/issues/12702#issuecomment-5132916625) on #12702 and the more general issue to track this at #13060). It seems like this and `SubmissionFileStageAccessPolicy` above have come up in at least a few different places of needing to have this kind of policy check outside of the context of the larger, non-internal `SubmissionFileAccessPolicy`. 

@asmecher, in #13060 you mention the possibility of moving some of these out of the internal namespace. It seems like this, `SubmissionRequiredPolicy` and `SubmissionFileStageAccessPolicy` have come up as a need outside of the internal policies. Would you be against moving these out of the internal namespace, or with an eye towards our security approach in general, did you have a different preference?

2026-08-19 21:56 UTC, ewhanson commented on api/v1/submissions/PKPSubmissionFileController.php
> +                    if (is_string($val)) {
You could use the helper [`paramToArray`](https://github.com/pkp/pkp-lib/blob/dcd67ebc72efc9773d7747072db1486c4c175521/includes/functions.php#L135-L148) instead of handling the parsing directly.

2026-08-23 10:38 UTC, merged