Download reviews from modal
pkp/pkp-lib pull request #10226
Opened 2024-07-19 16:59 UTC by MrRob100

https://github.com/pkp/pkp-lib/issues/9873

2024-08-02 09:43 UTC, MrRob100 commented
@jardakotesovec, for the download reviews feature I have had to add javascript to https://github.com/MrRob100/pkp-lib/blob/download-reviews-from-modal/templates/controllers/grid/users/reviewer/readReview.tpl . Is there a better way of including it in a js file rather than embedded? The only ways I can see are for forms. I would do it in vue but our select component wont match Devikas design shown here https://github.com/pkp/pkp-lib/issues/9873

2024-08-15 08:31 UTC, jardakotesovec commented
@MrRob100 
Apologies for delay.

It would be awesome if you could use this Vue.js component - https://main--6555d3db80418bb1681b8b17.chromatic.com/?path=/docs/components-dropdownactions--docs

Also if you could make sure that the indentation in readReview.tpl does not change so its lot easier to see whats new/different there.

And while you are on it if you could rebase, so it works correctly with latest main branch on ojs and ui-library.

Thank you!

2024-08-15 08:33 UTC, jardakotesovec commented
@Vitaliy-1 Could you have a look on the backend part of this. There are are some new dependencies to generate the pdf etc. And I think you have some experience with that?

2024-08-19 14:53 UTC, Vitaliy-1 requested changes
Hi @MrRob100. I left a couple of comments. My main suggestion is to add UFT-8 support for generated PDFs, is it something doable? Thanks, it looks great!

2024-08-19 14:53 UTC, Vitaliy-1 commented on classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php
> +        $submissionId = $request->getUserVar('submissionId');
The general idea is that we check if user is permitted to access the submission or other entity.

2024-09-10 13:33 UTC, MrRob100 commented on classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php
> +        $submissionId = $request->getUserVar('submissionId');
Hi @Vitaliy-1 Changes are in but `$reviewAssignment = $this->getAuthorizedContextObject(Application::ASSOC_TYPE_REVIEW_ASSIGNMENT);` seems to be null for any user. Could you have a look at this please?

2024-09-24 14:48 UTC, MrRob100 commented on classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php
> +        $reviewId = $request->getUserVar('reviewAssignmentId');
@Vitaliy-1 However the logic has been moved to a controller now so works differently

2024-10-04 03:45 UTC, ewhanson requested changes

2024-10-04 03:45 UTC, ewhanson commented on api/v1/reviews/PKPReviewController.php
> +        $mpdf = new Mpdf([
To aid in readability of this and the XML method below, could you break out the actual PDF/XML generation into separate functions so the API handling vs the PDF/XML generation are a bit easier to follow and separate? If these endpoints/controllers grow in the future, I can see wanting to extract the document generation out to separate classes as well.

2024-11-12 23:36 UTC, ewhanson requested changes

2024-11-14 17:56 UTC, merged