pkp/pkp-lib#10157 Moved issueIds out of of publication_settings
pkp/pkp-lib pull request #10298
Opened 2024-08-12 07:46 UTC by Hafsa-Naeem

fix #10157

2024-08-12 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/pkp-lib?pullRequest=10298) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/pkp-lib?pullRequest=10298) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/pkp-lib?pullRequest=10298) it.</sub>

2024-08-13 16:00 UTC, jonasraoni commented on classes/publication/Collector.php
> +     * @param array|null $issueIds An array of issue IDs to filter by, or null to remove the filter.
When possible, I think the shorter syntax is preferred:

```suggestion
     * @param ?int[] $issueIds An array of issue IDs to filter by, or null to remove the filter.
```

2024-08-13 16:02 UTC, jonasraoni commented on classes/galley/DAO.php
> +            ->when($issueId != null, fn (Builder $q) => $q->where('p.issue_id', '=', $issueId))
```suggestion
            ->when($issueId !== null, fn (Builder $q) => $q->where('p.issue_id', '=', $issueId))
```

2024-08-27 20:02 UTC, asmecher commented
@Hafsa-Naeem, the `issue_id` / `publication_id` relationship is only applicable to OJS, but we're adding it here to `pkp-lib` which will also affect OMP and OPS. Could you see if you can isolate the changes to OJS only? The best case would be for `issue_id` code only to appear in the OJS repo, but if it is necessary for some of those concerns to move into pkp-lib, then it would need to be an optional relationship.

2024-08-27 20:03 UTC, asmecher requested changes
https://github.com/pkp/pkp-lib/pull/10298#issuecomment-2313405065

2025-02-28 19:19 UTC, merged