pkp/pkp-lib#10336 Expose publication forms via API
pkp/pkp-lib pull request #10349
Opened 2024-08-29 04:35 UTC by taslangraham

2024-09-05 22:27 UTC, ewhanson requested changes

2024-09-05 22:27 UTC, ewhanson commented on api/v1/submissions/PKPSubmissionController.php
> +    protected function getContext(PKPRequest $request, Submission $submission)
Return type is missing.

2024-09-05 22:27 UTC, ewhanson commented on api/v1/submissions/PKPSubmissionController.php
> +    protected function getPublicationFormLocales(Context $context, Submission $submission)
Return type is missing.

2024-09-06 00:51 UTC, taslangraham commented on api/v1/submissions/PKPSubmissionController.php
> +    protected function getContext(PKPRequest $request, Submission $submission)
updated

2024-09-06 00:52 UTC, taslangraham commented on api/v1/submissions/PKPSubmissionController.php
> +    protected function getPublicationFormLocales(Context $context, Submission $submission)
updated

2024-09-06 04:00 UTC, ewhanson approved these changes

2024-09-06 14:59 UTC, merged