[TEST ONLY] send and accept invitation views and php integrations
pkp/pkp-lib pull request #10558
Opened 2024-10-24 14:01 UTC by ipula

2024-10-30 08:47 UTC, ipula commented on locale/en/invitation.po
> +msgstr "It should be 10 characters long and could be a combination of uppercase letters, lowercase letters or numbers"
its happens [here](https://github.com/ipula/ui-library/blob/d5e96c7853892d9dc5cfaaf51e395974a070ca89/src/pages/acceptInvitation/AcceptInvitationUserAccountDetails.vue#L14)

2024-10-30 08:50 UTC, ipula commented on locale/en/invitation.po
> +msgstr "It should be 12 characters long and should be a combination of uppercase letters, lowercase letters, numbers and symbols"
same as above.Now its only required 6 characters. I will ask @Devika008 for a new message

2024-10-30 12:17 UTC, withanage commented
@ewhanson 
> * The phrase "OJS" and "journal" are used throughout the locale keys. I've indicated these ones with comments, but I think for this PR it would probably be best to get this merged, and address that separately afterwards. So you can keep the comments there, but I wouldn't worry about them right now.
> 

The OJS specific locale were moved to OJS locale, so that other PKP applications may customize them easily.
https://github.com/pkp/ojs/pull/4497

2024-10-30 12:44 UTC, ipula commented on locale/en/invitation.po
> +msgstr "Cancel the invitation sent to {$givenName} {$familyName} will deactivate acceptance link sent via email. Here are the invitation details: "
https://github.com/orgs/craft-oa/projects/2/views/1?filterQuery=cancel&pane=issue&itemId=75533135&issue=craft-oa%7Cgdpr-invitation%7C15

2024-10-30 15:42 UTC, ipula commented
@ewhanson I made some changes to white-spaces and hide next button in ui-library in this [pr](https://github.com/pkp/ui-library/pull/439)

2024-10-30 16:27 UTC, ewhanson commented
> The OJS specific locale were moved to OJS locale, so that other PKP applications may customize them easily. [pkp/ojs#4497](https://github.com/pkp/ojs/pull/4497)

Thanks @withanage. Have PRs with equivalents been created for OPS and OMP been created? We'll need those too. Thanks!

2024-10-31 03:53 UTC, ewhanson requested changes
Thanks @ipula for the quick changes! Just a few other smaller style things along with a question about journal specific language for @withanage. Once that's taken care of it should be ready for merge!

2024-10-31 03:53 UTC, ewhanson commented on classes/invitation/stepTypes/SendInvitationStep.php
> +    public function getSteps(?Invitation $invitation, Context $context,?User $user): array
Space needed between `$context` and `?User`.

2024-10-31 03:53 UTC, ewhanson commented on locale/en/invitation.po
> +msgstr "Journal Masthead"
Anything journal-related should probably move to the applications as well. If you've already done this for the OJS language, could you do this for the word "journal" as well, @withanage?

2024-10-31 03:53 UTC, ewhanson commented on locale/en/invitation.po
> +msgstr "Journal Masthead"
Usage of journal. Should be moved to app. cc: @withanage.

2024-10-31 03:53 UTC, ewhanson commented on locale/en/invitation.po
> +msgstr "Send the user an email to let them know about the invitation, next steps, journal GDPR polices and ORCID verification"
Usage of journal. Should be moved to app. cc: @withanage.

2024-10-31 03:53 UTC, ewhanson commented on locale/en/invitation.po
> +msgstr "The user does not have a role in this journal"
Usage of journal. Should be moved to app. cc: @withanage.

2024-10-31 03:53 UTC, ewhanson commented on locale/en/invitation.po
> +msgid "userInvitation.search.userFound"
Usage of journal. Should be moved to app. cc: @withanage.

2024-10-31 03:53 UTC, ewhanson commented on templates/invitation/acceptInvitation.tpl
> +    <accept-invitation-page
These have been converted to spaces. The `.tpl` files should use tabs instead.

2024-10-31 03:53 UTC, ewhanson commented on templates/invitation/userInvitation.tpl
> +    <user-invitation-page
These have been converted to spaces. The `.tpl` files should use tabs instead.

2024-10-31 03:53 UTC, ewhanson commented on templates/management/access.tpl
> +            <user-invitation-manager></user-invitation-manager>
This line should use tabs like the rest of the file.

2024-10-31 13:15 UTC, withanage commented
@ewhanson  all the  strings with "Jourals"  were also moved to journal locale

2024-10-31 18:09 UTC, ewhanson approved these changes
Thanks so much, @ipula! Looks good now!

2024-10-31 18:09 UTC, merged