pkp/pkp-lib#1660 Customizable Reviewer Recommendations
pkp/pkp-lib pull request #10583
Opened 2024-11-06 11:16 UTC by touhidurabir

for pkp/pkp-lib#1660

2025-02-28 00:21 UTC, asmecher requested changes

2025-02-28 00:21 UTC, asmecher commented on api/v1/reviewers/recommendations/ReviewerRecommendationController.php
> + * @file api/v1/reviewers/recommendations/ReviewerRecommendationController.php
This handler doesn't appear to check that the recommendation being edited/deleted exists in the current context! The manage of one journal can edit and delete recommendations that belong to another.

2025-02-28 00:21 UTC, asmecher commented on classes/submission/reviewer/recommendation/Repository.php
> +            1 => 'reviewer.article.decision.accept', // SUBMISSION_REVIEWER_RECOMMENDATION_ACCEPT
I think it should be possible to eliminate the `value` column and just rely on a database ID. It would reduce the use of magic numbers, and mean that the options that ship with OJS are treated just like user-created options. To do this, `review_assignments.recommendation` would also need to be converted to a `recommendation_id` foreign key to the `reviewer_recommendations` table.

2025-02-28 00:21 UTC, asmecher commented on classes/userGroup/Repository.php
> +    public function getByRoleIds(array $roleIds, ?int $contextId, ?bool $default = null): LazyCollection
Is this change intentional/necessary?

2025-02-28 09:45 UTC, touhidurabir commented on api/v1/reviewers/recommendations/ReviewerRecommendationController.php
> + * @file api/v1/reviewers/recommendations/ReviewerRecommendationController.php
Isn't that handled by `ContextAccessPolicy` defined in `authorize` so that only those have access to context can access that api end point ? And we are restricting the roles to `admin, manager and editor` . 

Or perhaps I am misunderstanding something ?

2025-02-28 10:09 UTC, touhidurabir commented on classes/submission/reviewer/recommendation/Repository.php
> +            1 => 'reviewer.article.decision.accept', // SUBMISSION_REVIEWER_RECOMMENDATION_ACCEPT
@asmecher This is something I have been pondering for some time . What you have mentioned is one way to do it that I also thought about. But then we have some complex upgrade process as default values `1-6` is not available anymore when adding to table as primary `id` will be sequential . So if have 2 contexts , context-1 will have 1-6 and context-2 will have 7-12, so we have to update every review assignments for context-2 . Now for a large installation with many context and many review assignment, upgrade is even more time consuming
1. first need to create recommendations for context
2. map to value `1-6` with recommendations id
3. update all review assignments for that context . 

Also need a way to mark the default ones so that on local change, we can add new translations for the default ones (that is not difficult)

The current implementation does not require all these complex process and allow minimum changes to introduce this feature . Thats why I went with this path . But you are right about `magic numbers` and that can be the major motivation alter it other way as you have described .

2025-02-28 11:08 UTC, touhidurabir commented on classes/userGroup/Repository.php
> +    public function getByRoleIds(array $roleIds, ?int $contextId, ?bool $default = null): LazyCollection
Truthfully I don't actually remember . I will test and confirm .

2025-02-28 15:39 UTC, asmecher commented on classes/submission/reviewer/recommendation/Repository.php
> +            1 => 'reviewer.article.decision.accept', // SUBMISSION_REVIEWER_RECOMMENDATION_ACCEPT
If we were adding this as a brand new review feature, we would definitely use a foreign key rather than a `value` field. The only time we need to match a default is when we are adding a new language, and that's a boundary case (which I think is already matching on translation text, not value, right?) -- and that's a rare/boundary case already, so not justifying a different storage method.

The upgrade will be quick, even on large installs:

1. Add a `recommendation_id` column to `review_assignments`, default null, with a FK constraint
2. For each journal...
  1. Introduce default 6 options to `reviewer_recommendations`, keeping a PHP-side map from `recommendation` constant to `recommendation_id`
  2. For each default recommendation option (count=6),
    3. Update any review assignments to use the appropriate ID
3. Drop the `recommendation` column from `review_assignments`

That's a fixed number of queries per journal -- no need to e.g. execute anything e.g. per review assignment or per submission.

2025-02-28 15:40 UTC, asmecher commented on api/v1/reviewers/recommendations/ReviewerRecommendationController.php
> + * @file api/v1/reviewers/recommendations/ReviewerRecommendationController.php
Yes, but you're accepting any recommendation ID as user-supplied data -- and that recommendation might belong to another journal that the manager or editor doesn't manage.

2025-03-27 16:00 UTC, asmecher requested changes

2025-04-04 08:55 UTC, touhidurabir commented on classes/submission/reviewAssignment/ReviewAssignment.php
> +    public function setRecommendationId(int $recommendationId)
Yes, the column is nullable but it's by default . If we need to assign/set a recommendation id , then it should be a real existing reviewer_recommendation_id, no point to set null which is by default null via this method . And in the migration the relation is set to `set null` on delete of a recommendation .

2025-04-04 09:01 UTC, touhidurabir commented on classes/core/SettingsBuilder.php
> +    public function whereNotIn($column, $values, $boolean = 'and')
Not actually , see the 4th param when calling the `whereIn`  from the `whereNotId` which is set to `true` , which in general reverse of `whereIn` . This allow us to use the useful whereNotIn bit more easily like `->whereNotIn('columns_name', [])` instead `->whereIn('columns_name', [], 'and', true)` .

2025-04-04 09:06 UTC, touhidurabir commented on classes/migration/install/ReviewerSuggestionsMigration.php
> +        Schema::drop('reviewer_suggestions');
Not really , just best practice to have the related table drop first and then the main one which I forgot to do for reviewer suggestion . I have reverted this change .

2025-04-04 09:53 UTC, touhidurabir commented on classes/submission/reviewer/recommendation/RecommendationOption.php
> +    case DEACTIVE;
> But I'm not sure this enumeration is worth the extra code, when we could just as easily use the ?bool type instead with constants defined in the ReviewerRecommendation class.

True, it's just seems a bit unreadable by what we mean by true, false and null .

2025-04-04 10:15 UTC, touhidurabir commented on classes/submission/reviewAssignment/ReviewAssignment.php
> +    public function getLocalizedRecommendation(?Context $context = null): string
> This should be able to return a null (for cases where the recommendation hasn't been set)

This return an empty string if no recommendation yet as it's return a localized data which is being used many places (in template and translation replacement) . 

> that condition should be checked below, as otherwise I think there will be an error when trying to index an array by `null`

it's being check as `$options[$this->getReviewerRecommendationId()] ?? ''` .  Also previously we had it like 
```
$options = [
    "" => "choose one",
    1 => "accept",
    2 => "decline"
];
```
so in case of `$this->getReviewerRecommendationId()` is `null`, we used to get default `choose one` . Now that we plan to remove it from recommendation list as per https://github.com/pkp/pkp-lib/pull/10583#discussion_r2017008214 , this check will still handle array index by null case .

2025-04-05 00:07 UTC, asmecher commented on classes/core/SettingsBuilder.php
> +    public function whereNotIn($column, $values, $boolean = 'and')
Ah, I totally missed the 4th parameter.

2025-04-10 14:59 UTC, asmecher requested changes
Just a couple minor tweaks, thanks!

2025-04-10 14:59 UTC, asmecher commented on classes/submission/reviewAssignment/ReviewAssignment.php
>       * @return string
The `@return` is incorrect after this change. In this case it doesn't add anything, now that there's a typehint, so it should just be removed.

2025-04-10 14:59 UTC, asmecher commented on classes/submission/reviewer/recommendation/Repository.php
> +     * (Includes default '' => "Choose One" string.)
This comment isn't accurate.

2025-04-13 11:13 UTC, touhidurabir commented on classes/submission/reviewer/form/PKPReviewerReviewStep3Form.php
> +            'reviewerRecommendationId' => $this->getData('reviewerRecommendationId'), // assign the recommendation to the review assignment, if there was one.
This is added to `APP\submission\reviewer\form\ReviewerReviewStep3Form` which extends `PKPReviewerReviewStep3Form` as https://github.com/pkp/ojs/pull/4505/files#diff-7219eb555c9953733a864d839235582030193afbaf49b6efdcefc40460214a79R34-R43 .

2025-04-13 12:46 UTC, touhidurabir commented on classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php
> +    protected function getReviewerFrom(int $selectionType, ?Request $request = null): ReviewerForm
it's a typo .

2025-04-29 03:24 UTC, merged