Activity log not working
pkp/pkp-lib pull request #10635
Opened 2024-11-26 10:02 UTC by marcbria

Old issue fixed by Martin in 2022 but never committed. In short, users can't see the "activity log" of 3.2 submissions. Patched and tested in 3.3.0-19 without any collateral effect.

Full description here:
https://forum.pkp.sfu.ca/t/activity-log-not-work/71271/9

2024-11-26 14:02 UTC, kaitlinnewson commented on classes/services/PKPSubmissionFileService.inc.php
> +				return $reviewRound ? $reviewRound->getStageId() : null;
Based on the original forum post, I think this change should be on line 771 and not here.

2024-11-26 14:07 UTC, kaitlinnewson requested changes
Thanks @marcbria! Just one small change needed here.

2024-11-27 08:36 UTC, marcbria commented
Sorry a lot Kaitlin. I'm ashamed. 
Change made.

2024-11-27 13:53 UTC, kaitlinnewson approved these changes

2024-11-27 15:48 UTC, jonasraoni approved these changes

2024-11-27 15:52 UTC, merged