Permit the creation of grandchild themes
pkp/pkp-lib pull request #6191
Opened 2020-08-18 21:39 UTC by reaganch

Resolves the issue where a child of a child theme does not work as intended, reported as issue #4704.

The fix is based on suggestions by @Vitaliy-1 and @NateWr at https://forum.pkp.sfu.ca/t/trouble-creating-grandchild-theme/52803.

Sample theme for testing: [bnzseeManuscript.tar.gz](https://github.com/pkp/pkp-lib/files/5092994/bnzseeManuscript.tar.gz)

2020-08-18 21:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/pkp-lib?pullRequest=6191) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/pkp-lib?pullRequest=6191) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/pkp-lib?pullRequest=6191) it.</sub>

2020-08-19 09:00 UTC, NateWr requested changes
Thanks @reaganch! Just one minor change needed for code formatting. The tests are running against this at https://github.com/pkp/ojs/pull/2861. I'll post in #4704 where we're tracking this issue.

2020-08-19 11:05 UTC, reaganch commented on classes/template/PKPTemplateManager.inc.php
> +        }
Thanks for pointing this out. I've just converted those spaces to tabs and pushed another commit to my forked repo. Please let me know if I need to do anything else. This is my first ever pull request.

2020-08-19 12:52 UTC, merged

2020-08-19 12:53 UTC, NateWr commented on classes/template/PKPTemplateManager.inc.php
> +        }
Perfect, thanks!