pkp/pkp-lib#8562 Improve submission wizard after usability tests
pkp/pkp-lib pull request #8575
Opened 2023-01-26 15:27 UTC by NateWr

2023-01-26 15:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/pkp-lib?pullRequest=8575) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/pkp-lib?pullRequest=8575) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/pkp-lib?pullRequest=8575) it.</sub>

2023-01-31 15:56 UTC, jonasraoni requested changes
I didn't see anything besides the duplicated `define('FORM_TITLE_ABSTRACT', 'titleAbstract');`, the rest are just suggestions =]
ps: I didn't download the branch to test the interface.

2023-01-31 16:20 UTC, NateWr commented on classes/components/forms/publication/Details.php
> +define('FORM_TITLE_ABSTRACT', 'titleAbstract');
Good spot! That was extra from a copy/paste. :)

2023-01-31 16:21 UTC, NateWr commented on classes/components/forms/publication/Details.php
> +                'apiUrl' => str_replace('__vocab__', SubmissionKeywordDAO::CONTROLLED_VOCAB_SUBMISSION_KEYWORD, $suggestionUrlBase),
Using `{` with a string replace complicated the JavaScript a bit, so I used `__abcd__` instead. Happy to revise this in the future but will leave it as-is for now.

2023-01-31 16:24 UTC, NateWr commented on classes/components/forms/publication/Details.php
> +        string $suggestionUrlBase,
Neat! I didn't know that, thanks!

2023-02-02 10:35 UTC, merged