pkp/pkp-lib#9434 Allow plugin level API call
pkp/pkp-lib pull request #9451
Opened 2023-10-23 10:27 UTC by touhidurabir

for pkp/pkp-lib#9434

2023-11-09 22:43 UTC, asmecher requested changes
This is not a bad idea, @touhidurabir, but can we come back to it later? We don't yet have a required use case for a plugin to add its own namespace to the API, and this does build in greater complexity to the `APIHandler`. At some point (I hope sooner than later) we can continue to replace our own routing/dispatching code with Laravel's, building on your work with the Laravel API router; when we do that, the fewer cases we have to replicate in Laravel, the better.

2023-11-09 22:43 UTC, asmecher commented on classes/core/APIRouter.php
> + * Copyright (c) 2023 John Willinsky
(I'm not sure it's at all necessary, but our general practice is to extend the date when editing classes -- so these should be changed to `2014-2023` and `2000-2023`, not just `2023`.)

2023-11-13 08:13 UTC, touhidurabir commented
> This is not a bad idea, @touhidurabir, but can we come back to it later? We don't yet have a required use case for a plugin to add its own namespace to the API, and this does build in greater complexity to the APIHandler.

@asmecher I agree . This is something I did as just to show a proof of concept that allow us now an easier way to have this functionality . 

BTW, in the previous implementation of 3.3.0/3.4.0, we have hook to allow plugin to intervene the API endpoints , see at https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/handler/APIHandler.php#L192 . Now that we have moved to `Laravel Routing System` it's been removed and previous approach will not work . Do we need such functionality ? If so, we can bring in that part only which is included in this PR(in that case I can create a new issue and only port the changes for the part) . If no needed, we can leave it for now .

2024-06-27 01:11 UTC, asmecher commented on classes/core/APIRouter.php
> -    public function getRequestedOp(PKPRequest $request): string
Is this an accidental revert of adding typehints?

2024-06-27 01:12 UTC, asmecher commented on classes/core/PKPBaseController.php
> +        // When the routes are added to router as a closure/callbale from other section like from a
*callable

2024-07-04 23:06 UTC, asmecher requested changes
Just a few minor comments -- thanks, @touhidurabir!

2024-07-04 23:06 UTC, asmecher commented on classes/handler/APIHandler.php
> +        if (empty($this->routesFromHook)) {
I think these 3 lines can be removed.

2024-07-05 08:52 UTC, touhidurabir commented on classes/core/APIRouter.php
> +        $pathInfoArray = array_merge($context, $pathInfoArray);
rebased and reverted back .

2024-07-05 08:53 UTC, touhidurabir commented on classes/core/APIRouter.php
> +        if (strtolower($pathInfoParts[1]) === 'api') {
good catch , it's a leftover change from removing plugin own level api

2024-07-05 08:53 UTC, touhidurabir commented on classes/core/Dispatcher.php
> +     * @param PKPRequest    $request            The request object
reverted back

2024-07-05 08:53 UTC, touhidurabir commented on classes/handler/APIHandler.php
> +        if (empty($this->routesFromHook)) {
removed .

2024-07-05 08:55 UTC, touhidurabir commented
@asmecher all requested changes have been addressed. I see that you have already added the removed hook `APIHandler::endpoints` in the `Hook::addUnsupportedHooks` .

2024-07-05 23:06 UTC, asmecher commented
Thanks, @touhidurabir; this needs a rebase before it can be merged, and could you also run it past the developer who was looking for the feature, along with a link to your example plugin?

2024-07-29 15:30 UTC, merged