Publisher Library can swap files
pkp/pkp-lib pull request #9522
Opened 2023-11-17 19:44 UTC by wopsononock

Fixes #5780

2023-11-17 19:48 UTC, wopsononock commented
This PR supersedes #9482, which had problems with my commit name and email that I couldn't resolve without starting over. This addresses the code issues raised there and tests successfully with stable-3_4_0.

2023-11-17 20:57 UTC, asmecher requested changes
Just a few small changes to request, thanks!

2023-11-17 20:57 UTC, asmecher commented on classes/file/PKPLibraryFileManager.php
> +    function replaceFromTemporaryFile(object &$temporaryFile, int $libraryFileType, LibraryFile $libraryFile) {
`object` should be `TemporaryFile` (and a `use` statement for that should be added at the top).

2023-11-17 20:57 UTC, asmecher commented on classes/file/PKPLibraryFileManager.php
> +    function replaceFromTemporaryFile(object &$temporaryFile, int $libraryFileType, LibraryFile $libraryFile) {
Also, the reference isn't necessary here.

2023-11-17 20:57 UTC, asmecher commented on classes/file/PKPLibraryFileManager.php
> +     * @param $temporaryFile object
Should be `TemporaryFile`, not `object`

2023-11-17 20:57 UTC, asmecher commented on classes/file/PKPLibraryFileManager.php
> +    function &assignFromTemporaryFile(&$temporaryFile, $libraryFileType, $libraryFile) {
References are unnecessary here.

2023-12-12 17:25 UTC, wopsononock commented
@asmecher I made the changes you requested.

2023-12-13 01:47 UTC, merged