pkp/pkp-lib#9453 Let reviewers view their recommendations for previous rounds
pkp/pkp-lib pull request #9526
Opened 2023-11-21 20:48 UTC by nibou230

### How to test?

1. Make a submission and send it to the Review step.
2. Invite one reviewer.
3. Connect as reviewer and complete the review (fill the form and add a file).
4. As editor, Request revision and select Revisions will be subject to a new round of peer reviews.
5. As an author, submit revision.
6. As editor, open a 2nd round of review.
7. Invite the 1st round reviewer.
8. Connect as the reviewer.
9. On top of the review page, you should see the Round 1 bouton.
10. In the new window, the reviewer can access its answers (forms and files).

2023-12-11 16:53 UTC, Vitaliy-1 requested changes

2023-12-11 16:53 UTC, Vitaliy-1 commented on templates/controllers/modals/reviewRound/reviewRound.tpl
> +<div id="historyTab">
Some styling isn't aligned, like font size, padding/margin... Maybe using `FormBuilderVocabulary` can help? @jardakotesovec, what do you think?

2023-12-11 18:16 UTC, Vitaliy-1 commented on controllers/review/ReviewRoundModalHandler.php
> +		$this->addPolicy(new RoleBasedHandlerOperationPolicy(
@asmecher, what do you think about this?

2023-12-12 16:47 UTC, asmecher commented on templates/controllers/modals/reviewRound/reviewRound.tpl
> +					<p>{$declineEmail->getSubject()}<br />
Please review the Smarty template to make sure that content is escaped appropriately. Plaintext content should go through `|escape`, and limited HTML content (e.g. email bodies) should go through `|strip_unsafe_html`.

2024-02-26 12:56 UTC, pilasou commented
Hi @jardakotesovec, hi @asmecher, it seems that we are nearly there for this feature. Can you confirm if everything is OK?

2024-05-01 10:23 UTC, closed without merging

2024-05-01 10:23 UTC, defstat commented
Closed in favor of #9920