pkp/pkp-lib#8365 Remove vestiges of path info disabled mode support
pkp/pkp-lib pull request #9761
Opened 2024-02-22 19:19 UTC by asmecher

2024-03-08 18:07 UTC, bozana requested changes
Hi @asmecher, the functions in ConvertLogFile, as well as other classes/files that extends it, should not be removed -- the old log files could have been created with disabled path info and we want to provide re-processing of those log files too (at least for some time).
Thus, I think only changes in Core and upgrade script are needed here.

2024-03-08 18:07 UTC, bozana commented on classes/cliTool/traits/ConvertLogFile.php
> -
Nothing should be removed from this file -- I extra added the functions here to be able to parse the old log files that used disabled path info once all the code is removed :-)

2024-03-08 18:07 UTC, bozana commented on classes/migration/upgrade/v3_4_0/I8508_ConvertCurrentLogFile.php
> -    public function isPathInfoDisabled(): bool
Because this function is needed to be implemented -- it is an abstract function in ConvertLogFile, maybe to here only return false ?

2024-03-08 18:07 UTC, bozana commented on tools/convertApacheAccessLogFile.php
> -
This file should also not be changed...

2024-03-08 18:07 UTC, bozana commented on tools/convertUsageStatsLogFile.php
> -
And this one as well...

2024-03-14 15:08 UTC, merged

2024-03-14 15:08 UTC, asmecher commented
Thanks for the review, @bozana! I adjusted as you suggested and merged.